version: "3.0"

services:
  db:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=savefavdotcom
    ports:
      - 3306:3306
  app:
    image: savefavdotcom/stable:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
    tty: true
